include make.inc

all:
	$(MAKE) -C bench_potrf all
	$(MAKE) -C bench_trsm all
#	$(MAKE) -C bench_syrk all
#	$(MAKE) -C bench_gemm all

clean:
	$(MAKE) -C bench_potrf clean
	$(MAKE) -C bench_trsm clean
#	$(MAKE) -C bench_syrk clean
#	$(MAKE) -C bench_gemm clean
